- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3  # Use the ref you want to point at
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer

  - id: flake8
    additional_dependencies:
    - "flake8-bandit==1.0.2"
    - "flake8-bugbear~=19.3.0"
    - "flake8-docstrings~=1.3.0"
    - "flake8-import-order~=0.18.1"
    - "flake8-string-format~=0.2.3"
    - "flake8-tidy-imports~=2.0.0"
    - "pep8-naming~=0.8.2"
    - "mccabe~=0.6.1"
    - "pydocstyle<4.0"

  - id: trailing-whitespace
    args: ["--markdown-linebreak-ext=md"]
