"""Fix branch <-> build relationship

Revision ID: 1371a0cbdc26
Revises: 8eabadc5eda8
Create Date: 2017-07-24 07:59:09.245651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1371a0cbdc26'
down_revision = '8eabadc5eda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
