"""Comment URL for posts

Revision ID: 1397f80e554b
Revises: 89871415a9c3
Create Date: 2017-07-03 14:12:42.139936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1397f80e554b'
down_revision = '89871415a9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_post', sa.Column('comment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_post', 'comment_url')
    # ### end Alembic commands ###
