"""Initial OAuth schema

Revision ID: 1b0e4e8e3680
Revises: 1371a0cbdc26
Create Date: 2017-09-13 22:36:13.600345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0e4e8e3680'
down_revision = '1371a0cbdc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accesstoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('oauth_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('display_description', sa.String(), nullable=True),
    sa.Column('display_icon', sa.String(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('app_secret', sa.String(), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id'),
    sa.UniqueConstraint('app_secret'),
    sa.UniqueConstraint('name')
    )
    op.create_table('oauth_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.Column('defunct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_client')
    op.drop_table('oauth_application')
    op.drop_table('oauth_accesstoken')
    # ### end Alembic commands ###
