"""OAuth stuff

Revision ID: 2c139efa98a6
Revises: 1b0e4e8e3680
Create Date: 2017-09-15 12:54:50.341495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c139efa98a6'
down_revision = '1b0e4e8e3680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_client', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'oauth_client', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_client', type_='foreignkey')
    op.drop_column('oauth_client', 'user_id')
    # ### end Alembic commands ###
