"""Add product table

Revision ID: 4d7dc047efed
Revises: 0c03b003c581
Create Date: 2017-06-24 16:57:44.004497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7dc047efed'
down_revision = '0c03b003c581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('url_github', sa.String(), nullable=True),
    sa.Column('url_circleci', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
