"""Email code length is not predictable

Revision ID: 5c7a728f2a53
Revises: ebaad2ec04db
Create Date: 2017-06-17 21:29:09.560347

"""
from alembic import op
import sqlalchemy as sa

# TODO: Investigate why this is

# revision identifiers, used by Alembic.
revision = '5c7a728f2a53'
down_revision = 'ebaad2ec04db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
