"""News post drafts

Revision ID: 89871415a9c3
Revises: e1e9540aba16
Create Date: 2017-06-30 23:55:05.016429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89871415a9c3'
down_revision = 'e1e9540aba16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_post', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_post', 'published')
    # ### end Alembic commands ###
