"""Basic product build setup

Revision ID: 8eabadc5eda8
Revises: 1397f80e554b
Create Date: 2017-07-23 16:04:01.101574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eabadc5eda8'
down_revision = '1397f80e554b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('release', sa.Boolean(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('state_text', sa.String(), nullable=True),
    sa.Column('commit_url', sa.String(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('downloads', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('url_circleci', sa.String(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['product_branch.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('num', 'product_id', 'branch_id', name='_product_build_uc'),
    sa.UniqueConstraint('url_circleci')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_build')
    # ### end Alembic commands ###
