"""Add branches

Revision ID: 95c3b9f7ca89
Revises: c02a0c2fb5a7
Create Date: 2017-06-25 01:41:31.285411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c3b9f7ca89'
down_revision = 'c02a0c2fb5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'product_id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('product', sa.Column('branches', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_unique_constraint(None, 'product', ['url_circleci'])
    op.create_unique_constraint(None, 'product', ['url_github'])
    op.create_unique_constraint(None, 'product', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'branches')
    op.drop_table('product_branch')
    # ### end Alembic commands ###
