"""Default branches for products

Revision ID: e1e9540aba16
Revises: 6f2212bbc07b
Create Date: 2017-06-27 12:16:31.798204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e9540aba16'
down_revision = '6f2212bbc07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('default_branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'product_branch', ['default_branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'default_branch_id')
    # ### end Alembic commands ###
