"""Adjust more OAuth stuff

Revision ID: f692c2bd5fe3
Revises: 6a9cee4abac1
Create Date: 2017-09-15 20:23:07.857637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f692c2bd5fe3'
down_revision = '6a9cee4abac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accesstoken', sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('oauth_client', 'defunct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_client', sa.Column('defunct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('oauth_accesstoken', 'scopes')
    # ### end Alembic commands ###
