"""
Django settings for glowstone project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from os import environ

DEBUG = "DEBUG" in environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

if DEBUG:
    SECRET_KEY = '!-qy_8m^s92gb$c14b0!+kk*e%x*iu-fph4gc+)oe1az^av4o('  # noqa: S105
else:
    SECRET_KEY = environ["SECRET_KEY"]

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    'glowstone.apps.index'

    'django_simple_bulma',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'glowstone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'glowstone', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'glowstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    import dj_database_url

    DATABASES = {'default': dj_database_url.config(conn_max_age=600)}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, 'glowstone', 'locale')]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_ROOT = environ.get('MEDIA_ROOT', 'media')
STATIC_ROOT = environ.get('STATIC_ROOT', 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'glowstone', 'static')]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    'django_simple_bulma.finders.SimpleBulmaFinder',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '%(asctime)s | %(process)d:%(thread)d | %(module)s | %(levelname)-8s | %(message)s'
            )
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'DEBUG' if DEBUG else 'ERROR'
        }
    }
}

# Custom settings for Crispyforms
CRISPY_ALLOWED_TEMPLATE_PACKS = (
    "bulma",
)

CRISPY_TEMPLATE_PACK = "bulma"

# Custom settings for django-simple-bulma
BULMA_SETTINGS = {
    "custom_scss": [
        "frontend/static/css/base/base.scss"
    ],
    "variables": {
        "primary": "#46d67b",

        "text": "hsl(0, 0%, 96%)",  # white-ter
        "text-invert": "findColorInvert($text)",
        "text-light": "darken($text, 30%)",
        "text-strong": "darken($text, 50%)",

        "title-color": "$text",
        "subtitle-color": "$text-light",
        "subtitle-strong-color": "$text-strong",

        "body-background-color": "hsl(0, 0%, 14%)",  # black-ter
        "navbar-background-color": "$body-background-color",
        "border": "lighten($body-background-color, 10%)",

        "green": "$primary",
        "link": "$primary",
        "link-hover": "darken($link, 20%)",

        "tag-background-color": "$border",
        "tag-color": "$text",

        "input-color": "$text",
        "input-background-color": "$body-background-color",
        "input-border-color": "$border",

        "input-hover-color": "$text",
        "input-hover-border-color": "lighten($border, 10%)",

        "input-focus-color": "$text",
        "input-focus-border-color": "$link",

        "input-disabled-color": "$border",
        "input-disabled-background-color": "$body-background-color",
        "input-disabled-border-color": "$border",

        "input-arrow": "$link",
        "input-icon-color": "$input-hover-border-color",
        "input-icon-active-color": "$text",

        "navbar-dropdown-border-top": "0",
        "navbar-dropdown-background-color": "$body-background-color",

        "navbar-item-color": "$text",
        "navbar-item-active-background-color": "$border",
        "navbar-item-hover-background-color": "$border",

        "navbar-dropdown-item-hover-color": "$text",
        "navbar-dropdown-item-hover-background-color": "$border",

        "navbar-dropdown-item-active-color": "$link",
        "navbar-dropdown-item-active-background-color": "$border",

        "navbar-divider-background-color": "$border",

        "pagination-color": "$text",
        "pagination-border-color": "$border",

        "pagination-hover-color": "primary",
        "pagination-hover-border-color": "$border",

        "pagination-focus-color": "$text",
        "pagination-focus-border-color": "$border",

        "pagination-active-color": "$text",
        "pagination-active-border-color": "$primary",

        "pagination-disabled-color": "$border",
        "pagination-disabled-background-color": "$body-background-color",
        "pagination-disabled-border-color": "$border",

        "pagination-current-color": "$text",
        "pagination-current-background-color": "$primary",
        "pagination-current-border-color": "$primary",

        "pagination-ellipsis-color": "$border",

        "footer-padding": "1rem 1.5rem 1rem",
    }
}
